
Vagrant.configure("2") do |config|

  #config.vm.box = "bento/centos-8"
  config.vm.box = "centos/8"

  config.vm.network :forwarded_port, guest: 22, host: 3422
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 8080, host: 8383

   config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end

end
