Vagrant.configure("2") do |config|
  config.vm.box = "debian/v12.20240212.1"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
  end

  config.vm.define "cli1" do |cli1|
    cli1.vm.hostname = "cli1"
    cli1.vm.network "private_network", ip: "192.168.10.2", virtualbox__intnet: "vlan1"
  end

  config.vm.define "cli2" do |cli2|
    cli2.vm.hostname = "cli2"
    cli2.vm.network "private_network", ip: "192.168.20.2", virtualbox__intnet: "vlan2"
  end

  config.vm.define "cli3" do |cli3|
    cli3.vm.hostname = "cli3"
    cli3.vm.network "private_network", ip: "192.168.20.3", virtualbox__intnet: "vlan2"
  end

  config.vm.define "bridge" do |bridge|
    bridge.vm.hostname = "bridge"
    bridge.vm.network "private_network", adapter: 2, auto_config: false, virtualbox__intnet: "vlan1"
    bridge.vm.network "private_network", adapter: 3, auto_config: false, virtualbox__intnet: "vlan2"
    bridge.vm.network "private_network", adapter: 4, auto_config: false, virtualbox__intnet: "trunk"
    bridge.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
        vb.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
    end
  end

  config.vm.define "srv" do |srv|
    srv.vm.hostname = "srv"
    srv.vm.network "private_network", auto_config: false, virtualbox__intnet: "trunk"
  end
end
