# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "onedemo" do |server|
  config.vm.box = "generic/centos8"
  config.vm.network "forwarded_port", guest: 80, host: 8888  
  config.vm.network "forwarded_port", guest: 5900, host: 5900

  config.vm.provider "virtualbox" do |vb|
  # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end

    server.vm.provision "shell",
      path: "minione.sh"
  end
end
